export interface BookEntry {
  file: string;
  name: string;
}

export const OLD_TESTAMENT_BOOKS: BookEntry[] = [
  { file: "01_Genesis", name: "Genesis" },
  { file: "02_Exodus", name: "Exodus" },
  { file: "03_Leviticus", name: "Leviticus" },
  { file: "04_Numbers", name: "Numbers" },
  { file: "05_Deuteronomy", name: "Deuteronomy" },
  { file: "06_Joshua", name: "Joshua" },
  { file: "07_Judges", name: "Judges" },
  { file: "08_Ruth", name: "Ruth" },
  { file: "09_I_Samuel", name: "1 Samuel" },
  { file: "10_II_Samuel", name: "2 Samuel" },
  { file: "11_I_Kings", name: "1 Kings" },
  { file: "12_II_Kings", name: "2 Kings" },
  { file: "13_I_Chronicles", name: "1 Chronicles" },
  { file: "14_II_Chronicles", name: "2 Chronicles" },
  { file: "15_Ezra", name: "Ezra" },
  { file: "16_Nehemiah", name: "Nehemiah" },
  { file: "17_Esther", name: "Esther" },
  { file: "18_Job", name: "Job" },
  { file: "19_Psalms", name: "Psalms" },
  { file: "20_Proverbs", name: "Proverbs" },
  { file: "21_Ecclesiastes", name: "Ecclesiastes" },
  { file: "22_Song_of_Solomon", name: "Song of Solomon" },
  { file: "23_Isaiah", name: "Isaiah" },
  { file: "24_Jeremiah", name: "Jeremiah" },
  { file: "25_Lamentations", name: "Lamentations" },
  { file: "26_Ezekiel", name: "Ezekiel" },
  { file: "27_Daniel", name: "Daniel" },
  { file: "28_Hosea", name: "Hosea" },
  { file: "29_Joel", name: "Joel" },
  { file: "30_Amos", name: "Amos" },
  { file: "31_Obadiah", name: "Obadiah" },
  { file: "32_Jonah", name: "Jonah" },
  { file: "33_Micah", name: "Micah" },
  { file: "34_Nahum", name: "Nahum" },
  { file: "35_Habakkuk", name: "Habakkuk" },
  { file: "36_Zephaniah", name: "Zephaniah" },
  { file: "37_Haggai", name: "Haggai" },
  { file: "38_Zechariah", name: "Zechariah" },
  { file: "39_Malachi", name: "Malachi" },
];

export const NEW_TESTAMENT_BOOKS: BookEntry[] = [
  { file: "40_Matthew", name: "Matthew" },
  { file: "41_Mark", name: "Mark" },
  { file: "42_Luke", name: "Luke" },
  { file: "43_John", name: "John" },
  { file: "44_Acts", name: "Acts" },
  { file: "45_Romans", name: "Romans" },
  { file: "46_I_Corinthians", name: "1 Corinthians" },
  { file: "47_II_Corinthians", name: "2 Corinthians" },
  { file: "48_Galatians", name: "Galatians" },
  { file: "49_Ephesians", name: "Ephesians" },
  { file: "50_Philippians", name: "Philippians" },
  { file: "51_Colossians", name: "Colossians" },
  { file: "52_I_Thessalonians", name: "1 Thessalonians" },
  { file: "53_II_Thessalonians", name: "2 Thessalonians" },
  { file: "54_I_Timothy", name: "1 Timothy" },
  { file: "55_II_Timothy", name: "2 Timothy" },
  { file: "56_Titus", name: "Titus" },
  { file: "57_Philemon", name: "Philemon" },
  { file: "58_Hebrews", name: "Hebrews" },
  { file: "59_James", name: "James" },
  { file: "60_I_Peter", name: "1 Peter" },
  { file: "61_II_Peter", name: "2 Peter" },
  { file: "62_I_John", name: "1 John" },
  { file: "63_II_John", name: "2 John" },
  { file: "64_III_John", name: "3 John" },
  { file: "65_Jude", name: "Jude" },
  { file: "66_Revelation_of_John", name: "Revelation" },
];
