import "../styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import { Header } from "./_components/Header";
import { ToastProvider } from "./_components/ToastProvider";

export const metadata: Metadata = {
  title: "ScriptAsync",
  // description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <TRPCReactProvider>
          <Header />
          <main className="mx-auto w-full max-w-5xl px-6 py-8">
            {children}
          </main>
          <ToastProvider />
        </TRPCReactProvider>
      </body>
    </html>
  );
}
