export interface BookEntry {
  file: string;
  name: string;
}

export const OLD_TESTAMENT_BOOKS: BookEntry[] = [
  { file: "01_Genesis", name: "Genesis" },
  { file: "02_Exodus", name: "Exodus" },
  { file: "03_Leviticus", name: "Leviticus" },
  { file: "04_Numbers", name: "Numbers" },
  { file: "05_Deuteronomy", name: "Deuteronomy" },
  { file: "06_Joshua", name: "Joshua" },
  { file: "07_Judges", name: "Judges" },
  { file: "08_Ruth", name: "Ruth" },
  { file: "09_I_Samuel", name: "1 Samuel" },
  { file: "10_II_Samuel", name: "2 Samuel" },
  { file: "11_I_Kings", name: "1 Kings" },
  { file: "12_II_Kings", name: "2 Kings" },
  { file: "13_I_Chronicles", name: "1 Chronicles" },
  { file: "14_II_Chronicles", name: "2 Chronicles" },
  { file: "15_Ezra", name: "Ezra" },
  { file: "16_Nehemiah", name: "Nehemiah" },
  { file: "17_Esther", name: "Esther" },
  { file: "18_Job", name: "Job" },
  { file: "19_Psalms", name: "Psalms" },
  { file: "20_Proverbs", name: "Proverbs" },
  { file: "21_Ecclesiastes", name: "Ecclesiastes" },
  { file: "22_Song_of_Solomon", name: "Song of Solomon" },
  { file: "23_Isaiah", name: "Isaiah" },
  { file: "24_Jeremiah", name: "Jeremiah" },
  { file: "25_Lamentations", name: "Lamentations" },
  { file: "26_Ezekiel", name: "Ezekiel" },
  { file: "27_Daniel", name: "Daniel" },
  { file: "28_Hosea", name: "Hosea" },
  { file: "29_Joel", name: "Joel" },
  { file: "30_Amos", name: "Amos" },
  { file: "31_Obadiah", name: "Obadiah" },
  { file: "32_Jonah", name: "Jonah" },
  { file: "33_Micah", name: "Micah" },
  { file: "34_Nahum", name: "Nahum" },
  { file: "35_Habakkuk", name: "Habakkuk" },
  { file: "36_Zephaniah", name: "Zephaniah" },
  { file: "37_Haggai", name: "Haggai" },
  { file: "38_Zechariah", name: "Zechariah" },
  { file: "39_Malachi", name: "Malachi" },
];

export const NEW_TESTAMENT_BOOKS: BookEntry[] = [
  { file: "40_Matthew", name: "Matthew" },
  { file: "41_Mark", name: "Mark" },
  { file: "42_Luke", name: "Luke" },
  { file: "43_John", name: "John" },
  { file: "44_Acts", name: "Acts" },
  { file: "45_Romans", name: "Romans" },
  { file: "46_I_Corinthians", name: "1 Corinthians" },
  { file: "47_II_Corinthians", name: "2 Corinthians" },
  { file: "48_Galatians", name: "Galatians" },
  { file: "49_Ephesians", name: "Ephesians" },
  { file: "50_Philippians", name: "Philippians" },
  { file: "51_Colossians", name: "Colossians" },
  { file: "52_I_Thessalonians", name: "1 Thessalonians" },
  { file: "53_II_Thessalonians", name: "2 Thessalonians" },
  { file: "54_I_Timothy", name: "1 Timothy" },
  { file: "55_II_Timothy", name: "2 Timothy" },
  { file: "56_Titus", name: "Titus" },
  { file: "57_Philemon", name: "Philemon" },
  { file: "58_Hebrews", name: "Hebrews" },
  { file: "59_James", name: "James" },
  { file: "60_I_Peter", name: "1 Peter" },
  { file: "61_II_Peter", name: "2 Peter" },
  { file: "62_I_John", name: "1 John" },
  { file: "63_II_John", name: "2 John" },
  { file: "64_III_John", name: "3 John" },
  { file: "65_Jude", name: "Jude" },
  { file: "66_Revelation_of_John", name: "Revelation" },
];

export const BOOK_CHAPTER_COUNTS: Record<string, number> = {
  "01_Genesis": 50,
  "02_Exodus": 40,
  "03_Leviticus": 27,
  "04_Numbers": 36,
  "05_Deuteronomy": 34,
  "06_Joshua": 24,
  "07_Judges": 21,
  "08_Ruth": 4,
  "09_I_Samuel": 31,
  "10_II_Samuel": 24,
  "11_I_Kings": 22,
  "12_II_Kings": 25,
  "13_I_Chronicles": 29,
  "14_II_Chronicles": 36,
  "15_Ezra": 10,
  "16_Nehemiah": 13,
  "17_Esther": 10,
  "18_Job": 42,
  "19_Psalms": 150,
  "20_Proverbs": 31,
  "21_Ecclesiastes": 12,
  "22_Song_of_Solomon": 8,
  "23_Isaiah": 66,
  "24_Jeremiah": 52,
  "25_Lamentations": 5,
  "26_Ezekiel": 48,
  "27_Daniel": 12,
  "28_Hosea": 14,
  "29_Joel": 3,
  "30_Amos": 9,
  "31_Obadiah": 1,
  "32_Jonah": 4,
  "33_Micah": 7,
  "34_Nahum": 3,
  "35_Habakkuk": 3,
  "36_Zephaniah": 3,
  "37_Haggai": 2,
  "38_Zechariah": 14,
  "39_Malachi": 4,
  "40_Matthew": 28,
  "41_Mark": 16,
  "42_Luke": 24,
  "43_John": 21,
  "44_Acts": 28,
  "45_Romans": 16,
  "46_I_Corinthians": 16,
  "47_II_Corinthians": 13,
  "48_Galatians": 6,
  "49_Ephesians": 6,
  "50_Philippians": 4,
  "51_Colossians": 4,
  "52_I_Thessalonians": 5,
  "53_II_Thessalonians": 3,
  "54_I_Timothy": 6,
  "55_II_Timothy": 4,
  "56_Titus": 3,
  "57_Philemon": 1,
  "58_Hebrews": 13,
  "59_James": 5,
  "60_I_Peter": 5,
  "61_II_Peter": 3,
  "62_I_John": 5,
  "63_II_John": 1,
  "64_III_John": 1,
  "65_Jude": 1,
  "66_Revelation_of_John": 22,
};
